### ISSUE TITLE
Can't add new pocket items.

### ISSUE THREAD

**Issue by suclogger** [fniephaus/alfred-pocket#11]
Now I can't add new items to pocket via this workflow.
I tried both hotkey and _pocket_add on my chrome,
and I tried authorize and updated the token saved in keychain,
but it just won't work.
It just happened a day or two,hoping you can fix this.

It is a great workflow .I use it nearly everyday.Thanks a lot for the brilliant work you have done.

**Comment by fniephaus** [comment]
@suclogger thanks for your bug report.
Could you please provide a debug log? Have you tried to just delete the token from your keychain and then re-authorize?
I am still able to add new links, so maybe there's something wrong with your setup...

**Comment by suclogger** [comment]
Yesterday was a holiday in China :) .Sorry for the late reply.
Here are some `debug message` from alfred console.

```code
---deautn---

19:28:04 workflow.py:2372 DEBUG    Deleted password : com.fniephaus.pocket:pocket_access_token
19:28:04 workflow.py:1152 DEBUG    Access token has been deleted successfully.
19:28:04 workflow.py:2008 DEBUG    Workflow finished in 0.021 seconds.


---reauth---

[STDERR: alfred.workflow.input.scriptfilter] 19:28:31 workflow.py:1972 DEBUG    Workflow version : 4.4.0
19:28:31 workflow.py:1387 DEBUG    Reading settings from `/Users/suclogger/Library/Application Support/Alfred 2/Workflow Data/com.fniephaus.pocket/settings.json` ...
19:28:31 workflow.py:2233 DEBUG    Update check not due
19:28:31 workflow.py:2133 DEBUG    Last run version : 4.4.0
19:28:31 workflow.py:2133 DEBUG    Last run version : 4.4.0
19:28:31 workflow.py:1610 DEBUG    Loading cached data from : /Users/suclogger/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.pocket/__workflow_update_status.cpickle
19:28:31 workflow.py:2181 DEBUG    update_data : {u'available': False}
19:28:36 workflow.py:1646 DEBUG    Cached data saved at : /Users/suclogger/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.pocket/pocket_request_token.cpickle
19:28:36 workflow.py:2163 DEBUG    Set last run version : 4.4.0
19:28:36 workflow.py:2008 DEBUG    Workflow finished in 4.151 seconds.

---add--

[INFO: alfred.workflow.input.keyword] Processing output 'alfred.workflow.action.script' with arg 'foo'
[ERROR: alfred.workflow.action.script] 19:34:57 workflow.py:1972 DEBUG    Workflow version : 4.4.0
50:60: syntax error: A property can’t go after this identifier. (-2740)
52:62: syntax error: A property can’t go after this identifier. (-2740)
19:34:57 workflow.py:2350 DEBUG    Got password : com.fniephaus.pocket:pocket_access_token
19:34:59 workflow.py:1990 ERROR    None. None
Traceback (most recent call last):
  File "/Users/suclogger/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.B66A96CA-91F7-4F2D-9353-2763A2A565B6/workflow/workflow.py", line 1983, in run
    func(self)
  File "pocket_save.py", line 16, in main
    if not add_item(get_browser_item(current_app), tags):
  File "pocket_save.py", line 75, in add_item
    url=item['url'], title=item['title'], tags=",".join(tags + ["alfred"]))
  File "/Users/suclogger/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.B66A96CA-91F7-4F2D-9353-2763A2A565B6/pocket_api.py", line 57, in wrapped
    return self.make_request(url, payload)
  File "/Users/suclogger/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.B66A96CA-91F7-4F2D-9353-2763A2A565B6/pocket_api.py", line 154, in make_request
    return cls._make_request(url, payload, headers)
  File "/Users/suclogger/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.B66A96CA-91F7-4F2D-9353-2763A2A565B6/pocket_api.py", line 147, in _make_request
    '%s. %s' % (error_msg, extra_info)
PocketException: None. None
19:34:59 workflow.py:2008 DEBUG    Workflow finished in 2.045 seconds.
[INFO: alfred.workflow.action.script] Processing output 'alfred.workflow.output.notification' with arg '<?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'com.fn
```

**Comment by fniephaus** [comment]
Thanks, @suclogger.
I will have a look into this as soon as I can.
