### ISSUE TITLE
Cannot add new link in with alfred-pocket

### ISSUE THREAD

**Issue by akougblenou** [fniephaus/alfred-pocket#50]
Hi,

I am trying to add new pocket items with alfred-pocket but when I do nothings happened, I got the debugging log here:
```
Starting debug for 'Pocket for Alfred'

[2018-04-17 07:00:38][ERROR: action.script] Traceback (most recent call last):
  File "pocket_save.py", line 10, in <module>
    POCKET = Pocket(config.CONSUMER_KEY, WF.get_password('pocket_access_token'))
  File "/Users/AKFourSe7en/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5674F772-4524-4D85-AAF9-E56EAC4B2D29/workflow/workflow.py", line 2617, in get_password
    account, '-g')
  File "/Users/AKFourSe7en/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5674F772-4524-4D85-AAF9-E56EAC4B2D29/workflow/workflow.py", line 2986, in _call_security
    raise PasswordNotFound()
workflow.workflow.PasswordNotFound
```

The log is pretty clear so my issue is that I don't know how to set the password on alfred-pocket, do I need to delete the workflow and add it once more ? is there another way ?

**Comment by AKFourSeven** [comment]
Nevermind I solved the issue, I just deleted the password from my keychain and try again and it worked fine, must have been an issue with OAuth or something.

**Comment by fniephaus** [comment]
No worries, glad to hear you were able to fix this yourself :) All the best!

**Comment by akougblenou** [comment]
I reinstalled my mac and I don't remember exactly how I solved the issue with the password.
I cannot find the password in the keychain in mac and when I start the debugger, this is what I get:

```js
Starting debug for 'Pocket for Alfred'

[2019-01-17 11:18:15][ERROR: action.script] Traceback (most recent call last):
  File "pocket_save.py", line 10, in <module>
    POCKET = Pocket(config.CONSUMER_KEY, WF.get_password('pocket_access_token'))
  File "/Users/akougblenou/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3C335435-A5C3-48EF-91F1-1B10212D220C/workflow/workflow.py", line 2442, in get_password
    account, '-g')
  File "/Users/akougblenou/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3C335435-A5C3-48EF-91F1-1B10212D220C/workflow/workflow.py", line 2811, in _call_security
    raise PasswordNotFound()
workflow.workflow.PasswordNotFound
```

Any thoughts on that ?

**Comment by fniephaus** [comment]
Hi @akougblenou,
Please check your keychains again, is there an entry called `com.fniephaus.pocket` somewhere? That one you need to delete. Alternatively, you can delete your token by typing `pocket wf:deauth` into Alfred. When you run the workflow the next time, the workflow should open the Pocket website asking for authorization. Once you have done that, it should work again.

Hope this helps,
Fabio

**Comment by akougblenou** [comment]
I do not see `com.fniephaus.pocket`anywhere and I am not sure but I tried typing this command directly into Alfred prompt but it just came back with error in the workflow:
```
10:50:13 workflow.py:2055 DEBUG    ---------- Pocket for Alfred (7.1.0) ----------
10:50:13 background.py:243 DEBUG    [__workflow_update_check] background job started
10:50:13 workflow.py:1462 DEBUG    reading settings from /Users/akougblenou/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.pocket/settings.json
10:50:13 workflow.py:2219 DEBUG    last run version: None
10:50:13 workflow.py:2761 DEBUG    deleted : u'/Users/akougblenou/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.pocket/__workflow_update_check.pid'
10:50:13 workflow.py:2761 DEBUG    deleted : u'/Users/akougblenou/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.pocket/com.fniephaus.pocket.log'
10:50:13 workflow.py:2074 ERROR    [Errno 2] No such file or directory: '/Users/akougblenou/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.pocket/__workflow_update_check.argcache'
Traceback (most recent call last):
  File "/Users/akougblenou/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3C335435-A5C3-48EF-91F1-1B10212D220C/workflow/workflow.py", line 2067, in run
    func(self)
  File "pocket.py", line 29, in main
    WF.clear_cache()
  File "/Users/akougblenou/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3C335435-A5C3-48EF-91F1-1B10212D220C/workflow/workflow.py", line 2606, in clear_cache
    self._delete_directory_contents(self.cachedir, filter_func)
  File "/Users/akougblenou/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3C335435-A5C3-48EF-91F1-1B10212D220C/workflow/workflow.py", line 2760, in _delete_directory_contents
    os.unlink(path)
OSError: [Errno 2] No such file or directory: '/Users/akougblenou/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.pocket/__workflow_update_check.argcache'
10:50:13 workflow.py:2076 INFO     for assistance, see: https://github.com/fniephaus/alfred-pocket/issues
10:50:13 workflow.py:2097 DEBUG    ---------- finished in 0.098s ----------
```
Maybe I put it in a wrong place...

**Comment by fniephaus** [comment]
Could please try reinstalling the workflow? What version of Alfred are you using?

**Comment by akougblenou** [comment]
I did try to reinstall a few times and:
- the first two hot keys (the ones that I used the most) are empty (well actually they are all empty, but maybe this is on purpose, I thought there was supposed to be the first hotkey to be equal to `^+L`)
- I am never prompt to authenticate to pocket
- I still get the password not found error

I am running on Alfred 3.7.1

**Comment by fniephaus** [comment]
Hi @akougblenou,
I'm afraid I can't explain why it's not working for you. I can only offer to remote debug this on your machine via a screen sharing session. Let me know if that's an option for you.

Fabio

**Comment by akougblenou** [comment]
I solved the issue:
- I went to "Edit Details" on the Workflow
- the website was set to your github
- I changed it to the home of pocket and finally got prompt to get the access

Now it works !

**Comment by fniephaus** [comment]
Perfect!
